// Code generated by mdatagen. DO NOT EDIT.

// Package metadata contains the build information for the
// exporter/hippocampus component.
package metadata

import (
	"go.opentelemetry.io/collector/component"
)

var (
	Type      = component.MustNewType("hippocampus")
	ScopeName = "github.com/fastbean-au/hippocampus-otel-collector/hippocampusexporter"
)

const (
	LogsStability = component.StabilityLevelDevelopment
)
